import React, { useState, useEffect, useCallback } from 'react';
import { 
  SimulationConfig, 
  LogEntry, 
  SimulationStatus, 
  CommitPlan 
} from './types';
import { GithubService } from './services/githubService';
import { GeminiService } from './services/geminiService';
import LogConsole from './components/LogConsole';
import SimulationPreview from './components/SimulationPreview';
import { 
  GitCommit, 
  Play, 
  Pause, 
  RotateCcw, 
  Settings, 
  Github, 
  Cpu, 
  ShieldAlert,
  Calendar,
  Layers,
  Sparkles
} from 'lucide-react';

// Default Configuration
const DEFAULT_CONFIG: SimulationConfig = {
  githubToken: '',
  owner: '',
  repo: '',
  branch: 'main',
  startDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  endDate: new Date().toISOString().split('T')[0],
  minCommitsPerDay: 1,
  maxCommitsPerDay: 5,
  weekendIntensity: 0.1,
  useGemini: false,
  apiKey: process.env.API_KEY || '',
  simulatePRs: true,
  simulateIssues: false,
  branchingStrategy: 'gitflow'
};

const App: React.FC = () => {
  const [config, setConfig] = useState<SimulationConfig>(DEFAULT_CONFIG);
  const [status, setStatus] = useState<SimulationStatus>(SimulationStatus.IDLE);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [plan, setPlan] = useState<CommitPlan[]>([]);
  const [progress, setProgress] = useState(0);
  
  // Refs for logic to avoid stale closures in loops
  const abortControllerRef = React.useRef<AbortController | null>(null);

  const addLog = useCallback((message: string, level: LogEntry['level'] = 'info', details?: string) => {
    setLogs(prev => [...prev, {
      id: Math.random().toString(36).substring(7),
      timestamp: new Date(),
      level,
      message,
      details
    }]);
  }, []);

  // Utility to generate the plan
  const generatePlan = useCallback(() => {
    const start = new Date(config.startDate);
    const end = new Date(config.endDate);
    const newPlan: CommitPlan[] = [];
    
    let current = new Date(start);
    while (current <= end) {
      const isWeekend = current.getDay() === 0 || current.getDay() === 6;
      let count = 0;
      
      // Basic probability logic
      if (!isWeekend || Math.random() < config.weekendIntensity) {
        const range = config.maxCommitsPerDay - config.minCommitsPerDay;
        count = Math.floor(Math.random() * range) + config.minCommitsPerDay;
        
        // Randomly skip days to look natural
        if (Math.random() > 0.8) count = 0;
      }

      if (count > 0) {
        newPlan.push({
          date: new Date(current),
          count,
          messages: Array(count).fill('update') // Placeholder
        });
      }
      
      current.setDate(current.getDate() + 1);
    }
    setPlan(newPlan);
    setStatus(SimulationStatus.PLANNING);
    addLog(`Plan generated: ${newPlan.reduce((acc, d) => acc + d.count, 0)} commits over ${newPlan.length} active days.`, 'success');
  }, [config, addLog]);

  // Main Execution Logic
  const runSimulation = async () => {
    if (!config.githubToken || !config.repo || !config.owner) {
        addLog('Missing configuration details.', 'error');
        return;
    }

    if (plan.length === 0) {
        generatePlan(); // Ensure plan exists
    }

    setStatus(SimulationStatus.RUNNING);
    addLog('Starting simulation engine...', 'info');

    const gh = new GithubService(config.githubToken, config.owner, config.repo);
    const gemini = config.useGemini && config.apiKey ? new GeminiService(config.apiKey) : null;

    try {
        // 1. Verify Repo
        const exists = await gh.verifyRepo();
        if (!exists) {
            addLog(`Repository ${config.owner}/${config.repo} not found. Attempting creation...`, 'warning');
            await gh.createRepo('Generated by GitChronicle');
            addLog('Repository created successfully.', 'success');
        } else {
            addLog(`Connected to ${config.owner}/${config.repo}`, 'success');
        }

        // 2. Get HEAD reference
        let currentHeadSha = '';
        try {
            const refData = await gh.getRef(`heads/${config.branch}`);
            currentHeadSha = refData.object.sha;
        } catch (e) {
            // If branch doesn't exist (empty repo), we might need to initialize
            addLog('Could not find branch. Assuming empty repo. Initializing...', 'warning');
            const blobSha = await gh.createBlob('# GitChronicle History');
            const treeSha = await gh.createTree('', [{ path: 'README.md', content: 'Initialized by GitChronicle' }]);
            // Initial commit
            currentHeadSha = await gh.createCommit('Initial commit', treeSha, '', new Date(config.startDate));
            // Create ref
            await gh.createRef(`refs/heads/${config.branch}`, currentHeadSha);
        }

        addLog(`Starting HEAD: ${currentHeadSha.substring(0, 7)}`, 'info');

        let totalCommits = 0;
        const totalPlannedCommits = plan.reduce((acc, p) => acc + p.count, 0);

        // 3. Loop through plan
        for (const day of plan) {
            if (abortControllerRef.current?.signal.aborted) throw new Error('Simulation aborted');

            for (let i = 0; i < day.count; i++) {
                // Generate Content
                const timestamp = new Date(day.date);
                // Spread commits throughout the workday (9-17)
                timestamp.setHours(9 + Math.floor(Math.random() * 8), Math.floor(Math.random() * 60));

                let message = `update: routine maintenance ${new Date().getTime()}`;
                let fileContent = `// Timestamp: ${timestamp.toISOString()}\nconsole.log("Work done");`;
                const filename = `src/feature-${Math.floor(Math.random() * 100)}.ts`;

                if (gemini) {
                    message = await gemini.generateCommitMessage(`Update for ${filename}`);
                    fileContent = await gemini.generateCodeSnippet(filename);
                }

                // Execute Git Operations (Low Level)
                // a. Create Blob
                const blobSha = await gh.createBlob(fileContent);
                
                // b. Get Current Tree to modify? 
                // Optimization: Just create a tree based on previous commit's tree, adding one file.
                // We need the tree SHA of the *currentHeadSha*
                const parentCommit = await gh.getCommit(currentHeadSha);
                const baseTreeSha = parentCommit.tree.sha;

                // c. Create new Tree
                const newTreeSha = await gh.createTree(baseTreeSha, [{ path: filename, content: fileContent }]);

                // d. Create Commit
                // Add co-author occasionally
                const coAuthors = Math.random() > 0.8 ? ['simulate-bot <bot@example.com>'] : [];
                
                const newCommitSha = await gh.createCommit(
                    message,
                    newTreeSha,
                    currentHeadSha,
                    timestamp,
                    coAuthors
                );

                // e. Move Head
                await gh.updateRef(`heads/${config.branch}`, newCommitSha);
                currentHeadSha = newCommitSha;

                totalCommits++;
                setProgress((totalCommits / totalPlannedCommits) * 100);
                addLog(`Committed: ${message}`, 'success', `SHA: ${newCommitSha.substring(0,7)} | Date: ${timestamp.toLocaleDateString()}`);

                // Rate limit guard
                await new Promise(r => setTimeout(r, 500)); // 500ms delay between ops
            }
        }

        setStatus(SimulationStatus.COMPLETED);
        addLog('Simulation completed successfully!', 'success');

    } catch (error: any) {
        setStatus(SimulationStatus.ERROR);
        addLog(error.message || 'Unknown error occurred', 'error');
    }
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 flex flex-col md:flex-row font-sans">
      
      {/* Sidebar Controls */}
      <aside className="w-full md:w-96 bg-slate-900 border-r border-slate-800 flex flex-col h-screen sticky top-0 overflow-y-auto z-10">
        <div className="p-6 border-b border-slate-800">
            <div className="flex items-center gap-3 mb-2">
                <GitCommit className="w-8 h-8 text-indigo-500" />
                <h1 className="text-xl font-bold text-white tracking-tight">GitChronicle</h1>
            </div>
            <p className="text-xs text-slate-500">History Simulation Bot</p>
        </div>

        <div className="p-6 space-y-6 flex-1">
            
            {/* Credentials */}
            <div className="space-y-4">
                <div className="flex items-center gap-2 text-indigo-400 font-semibold text-sm uppercase tracking-wider">
                    <Settings className="w-4 h-4" /> Configuration
                </div>
                
                <div className="space-y-2">
                    <label className="text-xs font-medium text-slate-400">GitHub Token (PAT)</label>
                    <input 
                        type="password" 
                        value={config.githubToken}
                        onChange={e => setConfig({...config, githubToken: e.target.value})}
                        className="w-full bg-slate-950 border border-slate-700 rounded px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none transition-colors"
                        placeholder="ghp_..."
                    />
                </div>
                
                <div className="grid grid-cols-2 gap-2">
                    <div className="space-y-2">
                        <label className="text-xs font-medium text-slate-400">Owner</label>
                        <input 
                            type="text" 
                            value={config.owner}
                            onChange={e => setConfig({...config, owner: e.target.value})}
                            className="w-full bg-slate-950 border border-slate-700 rounded px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none"
                            placeholder="username"
                        />
                    </div>
                    <div className="space-y-2">
                        <label className="text-xs font-medium text-slate-400">Repo</label>
                        <input 
                            type="text" 
                            value={config.repo}
                            onChange={e => setConfig({...config, repo: e.target.value})}
                            className="w-full bg-slate-950 border border-slate-700 rounded px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none"
                            placeholder="project-x"
                        />
                    </div>
                </div>
            </div>

            {/* Strategy */}
            <div className="space-y-4 pt-4 border-t border-slate-800">
                <div className="flex items-center gap-2 text-indigo-400 font-semibold text-sm uppercase tracking-wider">
                    <Calendar className="w-4 h-4" /> Timeline Strategy
                </div>
                
                <div className="grid grid-cols-2 gap-2">
                     <div className="space-y-2">
                        <label className="text-xs font-medium text-slate-400">Start Date</label>
                        <input 
                            type="date" 
                            value={config.startDate}
                            onChange={e => setConfig({...config, startDate: e.target.value})}
                            className="w-full bg-slate-950 border border-slate-700 rounded px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none text-slate-400"
                        />
                    </div>
                    <div className="space-y-2">
                        <label className="text-xs font-medium text-slate-400">End Date</label>
                        <input 
                            type="date" 
                            value={config.endDate}
                            onChange={e => setConfig({...config, endDate: e.target.value})}
                            className="w-full bg-slate-950 border border-slate-700 rounded px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none text-slate-400"
                        />
                    </div>
                </div>

                <div className="space-y-2">
                     <div className="flex justify-between text-xs text-slate-400">
                        <span>Intensity (Commits/Day)</span>
                        <span>{config.minCommitsPerDay} - {config.maxCommitsPerDay}</span>
                     </div>
                     <input 
                        type="range"
                        min="1" max="20"
                        value={config.maxCommitsPerDay}
                        onChange={e => setConfig({...config, maxCommitsPerDay: parseInt(e.target.value)})}
                        className="w-full h-1 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-indigo-500"
                     />
                </div>
            </div>

            {/* AI Integration */}
            <div className="space-y-4 pt-4 border-t border-slate-800">
                <div className="flex items-center gap-2 text-indigo-400 font-semibold text-sm uppercase tracking-wider">
                    <Sparkles className="w-4 h-4" /> AI Content
                </div>
                
                <label className="flex items-center gap-3 cursor-pointer group">
                    <div className={`w-10 h-6 rounded-full p-1 transition-colors duration-200 ${config.useGemini ? 'bg-indigo-600' : 'bg-slate-700'}`}>
                        <div className={`w-4 h-4 rounded-full bg-white transition-transform duration-200 ${config.useGemini ? 'translate-x-4' : ''}`} />
                    </div>
                    <span className="text-sm text-slate-300 group-hover:text-white transition-colors">Enable Gemini AI</span>
                    <input 
                        type="checkbox" 
                        className="hidden" 
                        checked={config.useGemini}
                        onChange={e => setConfig({...config, useGemini: e.target.checked})}
                    />
                </label>

                {config.useGemini && (
                     <div className="space-y-2 animate-fade-in">
                        <label className="text-xs font-medium text-slate-400">Gemini API Key</label>
                        <input 
                            type="password" 
                            value={config.apiKey}
                            onChange={e => setConfig({...config, apiKey: e.target.value})}
                            className="w-full bg-slate-950 border border-slate-700 rounded px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none placeholder-slate-600"
                            placeholder="AIzaSy..."
                        />
                    </div>
                )}
            </div>

        </div>

        <div className="p-6 border-t border-slate-800 bg-slate-900 sticky bottom-0">
             {status === SimulationStatus.RUNNING ? (
                 <button 
                    disabled 
                    className="w-full bg-slate-800 text-slate-400 py-3 rounded-md font-medium flex items-center justify-center gap-2 cursor-not-allowed"
                >
                    <Layers className="animate-spin w-4 h-4" /> Processing...
                 </button>
             ) : (
                <div className="grid grid-cols-2 gap-2">
                    <button 
                        onClick={generatePlan}
                        className="bg-slate-800 hover:bg-slate-700 text-white py-3 rounded-md font-medium transition-colors"
                    >
                        Generate Plan
                    </button>
                    <button 
                        onClick={runSimulation}
                        disabled={plan.length === 0}
                        className={`py-3 rounded-md font-medium flex items-center justify-center gap-2 transition-colors ${
                            plan.length === 0 
                            ? 'bg-indigo-900/50 text-indigo-300/50 cursor-not-allowed' 
                            : 'bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg shadow-indigo-500/20'
                        }`}
                    >
                        <Play className="w-4 h-4 fill-current" /> Start Bot
                    </button>
                </div>
             )}
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col h-screen overflow-hidden relative">
        
        {/* Header */}
        <header className="h-16 border-b border-slate-800 flex items-center justify-between px-8 bg-slate-950/50 backdrop-blur-sm z-10">
            <div className="flex items-center gap-4">
                <div className={`px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide flex items-center gap-2 ${
                    status === SimulationStatus.RUNNING ? 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/20' :
                    status === SimulationStatus.COMPLETED ? 'bg-green-500/10 text-green-400 border border-green-500/20' :
                    status === SimulationStatus.ERROR ? 'bg-red-500/10 text-red-400 border border-red-500/20' :
                    'bg-slate-800 text-slate-400'
                }`}>
                    <div className={`w-2 h-2 rounded-full ${
                        status === SimulationStatus.RUNNING ? 'bg-indigo-400 animate-pulse' :
                        status === SimulationStatus.COMPLETED ? 'bg-green-400' :
                        status === SimulationStatus.ERROR ? 'bg-red-400' :
                        'bg-slate-400'
                    }`} />
                    {status}
                </div>
            </div>
            
            <div className="flex items-center gap-6">
                <div className="text-right">
                    <p className="text-xs text-slate-500 uppercase tracking-wider">Target Repository</p>
                    <p className="text-sm font-mono text-slate-200">{config.owner || '---'} / {config.repo || '---'}</p>
                </div>
                <Github className="w-6 h-6 text-slate-600" />
            </div>
        </header>

        {/* Dashboard Content */}
        <div className="flex-1 overflow-y-auto p-8 space-y-6 scroll-smooth">
            
            {/* Stats Row */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="bg-slate-900 border border-slate-800 rounded-lg p-5 flex flex-col justify-between relative overflow-hidden group hover:border-indigo-500/50 transition-colors">
                    <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                        <GitCommit className="w-16 h-16" />
                    </div>
                    <div>
                        <p className="text-slate-400 text-xs font-semibold uppercase tracking-wider mb-1">Total Planned Commits</p>
                        <h3 className="text-3xl font-mono text-white">
                            {plan.reduce((acc, p) => acc + p.count, 0)}
                        </h3>
                    </div>
                    <div className="w-full bg-slate-800 h-1 mt-4 rounded-full overflow-hidden">
                        <div className="h-full bg-indigo-500 transition-all duration-500" style={{ width: `${progress}%` }} />
                    </div>
                </div>

                <div className="bg-slate-900 border border-slate-800 rounded-lg p-5 flex flex-col justify-between relative overflow-hidden group hover:border-emerald-500/50 transition-colors">
                    <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                        <Calendar className="w-16 h-16" />
                    </div>
                    <div>
                        <p className="text-slate-400 text-xs font-semibold uppercase tracking-wider mb-1">Active Days</p>
                        <h3 className="text-3xl font-mono text-white">{plan.length}</h3>
                    </div>
                    <p className="text-xs text-slate-500 mt-4">Across {(new Date(config.endDate).getTime() - new Date(config.startDate).getTime()) / (1000 * 3600 * 24)} days span</p>
                </div>

                <div className="bg-slate-900 border border-slate-800 rounded-lg p-5 flex flex-col justify-between relative overflow-hidden group hover:border-amber-500/50 transition-colors">
                     <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                        <Cpu className="w-16 h-16" />
                    </div>
                    <div>
                        <p className="text-slate-400 text-xs font-semibold uppercase tracking-wider mb-1">AI Integration</p>
                        <h3 className="text-3xl font-mono text-white">
                            {config.useGemini ? 'Active' : 'Disabled'}
                        </h3>
                    </div>
                     <p className="text-xs text-slate-500 mt-4">
                        {config.useGemini 
                        ? 'Generative messages & code enabled' 
                        : 'Using static templates'}
                    </p>
                </div>
            </div>

            {/* Visualization */}
            <SimulationPreview plan={plan} />

            {/* Console */}
            <div className="flex-1 min-h-[400px]">
                <LogConsole logs={logs} />
            </div>

        </div>

      </main>
    </div>
  );
};

export default App;